version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "ts-*"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@types/*"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "luxfi/bridge-maintainers"
    
  # Enable version updates for Go modules  
  - package-ecosystem: "gomod"
    directory: "/mpc-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      lux-dependencies:
        patterns:
          - "github.com/luxfi/*"
      infrastructure:
        patterns:
          - "github.com/nats-io/*"
          - "github.com/hashicorp/*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    reviewers:
      - "luxfi/mpc-maintainers"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "luxfi/devops"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/app/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "luxfi/devops"

  # Enable security updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
    reviewers:
      - "luxfi/security"
    pull-request-branch-name:
      separator: "-"