services:
  # Infrastructure Services
  nats:
    image: nats:2.10-alpine
    container_name: bridge-nats
    ports:
      - "4223:4222"
      - "8223:8222"
    command: "-js -m 8222 --store_dir /data"
    volumes:
      - nats-data:/data
    networks:
      - bridge-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 5s
      timeout: 3s
      retries: 5

  consul:
    image: hashicorp/consul:1.16
    container_name: bridge-consul
    ports:
      - "8501:8500"
      - "8602:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data
    networks:
      - bridge-network
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 3s
      retries: 5

  # MPC Nodes (3 nodes for 2-of-3 threshold)
  mpc-node-0:
    image: ghcr.io/luxfi/lux-mpc:latest
    container_name: bridge-mpc-0
    environment:
      - NODE_ID=mpc-node-0
      - NODE_PORT=6000
      - NATS_URL=nats://nats:4222
      - CONSUL_URL=http://consul:8500
      - DATA_DIR=/data/mpc
      - LOG_LEVEL=info
    volumes:
      - mpc-data-0:/data/mpc
    ports:
      - "6000:6000"
    networks:
      - bridge-network
    depends_on:
      nats:
        condition: service_healthy
      consul:
        condition: service_healthy

  mpc-node-1:
    image: ghcr.io/luxfi/lux-mpc:latest
    container_name: bridge-mpc-1
    environment:
      - NODE_ID=mpc-node-1
      - NODE_PORT=6000
      - NATS_URL=nats://nats:4222
      - CONSUL_URL=http://consul:8500
      - DATA_DIR=/data/mpc
      - LOG_LEVEL=info
    volumes:
      - mpc-data-1:/data/mpc
    ports:
      - "6001:6000"
    networks:
      - bridge-network
    depends_on:
      nats:
        condition: service_healthy
      consul:
        condition: service_healthy

  mpc-node-2:
    image: ghcr.io/luxfi/lux-mpc:latest
    container_name: bridge-mpc-2
    environment:
      - NODE_ID=mpc-node-2
      - NODE_PORT=6000
      - NATS_URL=nats://nats:4222
      - CONSUL_URL=http://consul:8500
      - DATA_DIR=/data/mpc
      - LOG_LEVEL=info
    volumes:
      - mpc-data-2:/data/mpc
    ports:
      - "6002:6000"
    networks:
      - bridge-network
    depends_on:
      nats:
        condition: service_healthy
      consul:
        condition: service_healthy

  # Database
  postgres:
    image: postgres:15-alpine
    container_name: bridge-postgres
    environment:
      - POSTGRES_USER=bridge
      - POSTGRES_PASSWORD=bridge
      - POSTGRES_DB=bridge
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - bridge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Bridge Server
  bridge-server:
    image: ghcr.io/luxfi/bridge-server:latest
    container_name: bridge-server
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://bridge:bridge@postgres:5432/bridge
      - NATS_URL=nats://nats:4222
      - CONSUL_URL=http://consul:8500
      - NODE_ID=bridge-server-0
      - MPC_THRESHOLD=2
      - MPC_TOTAL_NODES=3
      - MPC_KEY_PREFIX=bridge/mpc
    ports:
      - "5000:5000"
    networks:
      - bridge-network
    depends_on:
      - postgres
      - nats
      - consul
      - mpc-node-0
      - mpc-node-1
      - mpc-node-2
    volumes:
      - ./app/server:/app
      - /app/node_modules
    command: npm run dev

  # Bridge UI
  bridge-ui:
    image: ghcr.io/luxfi/bridge-ui:latest
    container_name: bridge-ui
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_CHAIN_ENV=local
    ports:
      - "3000:3000"
    networks:
      - bridge-network
    depends_on:
      - bridge-server
    volumes:
      - ./app/bridge:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  nats-data:
  consul-data:
  mpc-data-0:
  mpc-data-1:
  mpc-data-2:
  postgres-data:

networks:
  bridge-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16