packages:
  - 'app/*'
  - 'pkg/*'

catalog:
  '@hanzo/auth': 2.5.2
  '@hanzo/commerce': 7.3.4
  '@hanzo/ui': 4.4.1
  '@luxfi/core': 10.0.0
  '@luxfi/ui': 5.5.1
  '@luxfi/data': 1.0.9
  '@types/node': 20.14.15
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  lucide-react: 0.456.0
  react-hook-form: 7.51.4
  next: 14.2.16
  react: 18.3.1
  react-dom: 18.3.1
  tailwindcss: 3.4.14
  typescript: 5.7.2
