apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: caddyfile  
data:  
  Caddyfile: |  
    {  
      email jackson@lux.network  
    }  

    # Redirect HTTP to HTTPS  
    http:// {  
        redir https://{host}{uri}  # Redirect all HTTP traffic to HTTPS  
    }  

    teleport.lux.network {  
      # Redirect HTTP to HTTPS (optional)  
      redir http://{host}{uri} 301

      handle /node0/* {
        reverse_proxy mpc-node-0:6000  
      }  

      handle /node1/* {  
        reverse_proxy mpc-node-1:6000  
      }  

      handle /node2/* {  
        reverse_proxy mpc-node-2:6000  
      }  

      # Optional: Health check endpoint  
      handle /healthz {  
        respond "OK" 200  
      }  
    }