apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
data:
  Caddyfile: |
    :80 {
      # Handle requests to /node0 and its subpaths
      handle_path /node0* {
        reverse_proxy mpc-node-0:6000
      }

      # Handle requests to /node1 and its subpaths
      handle_path /node1* {
        reverse_proxy mpc-node-1:6000
      }

      # Handle requests to /node2 and its subpaths
      handle_path /node2* {
        reverse_proxy mpc-node-2:6000
      }

      # Catch-all for other requests, return 404 Not Found
      handle {
        respond "Not Found" 404
      }
    }

