# apiVersion: v1  
# kind: ConfigMap  
# metadata:  
#   name: caddyfile  
# data:  
#   Caddyfile: |
#     {  
#       email jackson@lux.network
#     }

#     # Redirect HTTP to HTTPS  
#     http:// {
#         redir https://{host}{uri}  # Redirect all HTTP traffic to HTTPS  
#     }

#     teleport.lux.network {  
#       reverse_proxy /node0/* mpc-node-0:6000  
#       reverse_proxy /node1/* mpc-node-1:6000  
#       reverse_proxy /node2/* mpc-node-2:6000
#     }
apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: caddyfile  
data:  
  Caddyfile: |  
    {  
      email jackson@lux.network  
      # Uncomment the next line if you want to use the staging environment for testing  
      # acme_ca https://acme-staging-v02.api.letsencrypt.org/directory  
    }  

    # Redirect HTTP to HTTPS  
    http:// {  
      redir https://{host}{uri} 301  
    }  

    teleport.lux.network {  
      # Global options  
      tls {  
        protocols tls1.2 tls1.3  
      }  
      
      # Logging (optional)  
      log {  
        output file /var/log/caddy/access.log  
        format json  
      }  

      # CORS headers (if needed)  
      header {  
        Access-Control-Allow-Origin *  
        Access-Control-Allow-Methods "GET, POST, OPTIONS"  
        Access-Control-Allow-Headers "Origin, Content-Type, Accept"  
      }  

      # Reverse proxy rules  
      handle /node0/* {  
        reverse_proxy mpc-node-0:6000  
      }  
      handle /node1/* {  
        reverse_proxy mpc-node-1:6000  
      }  
      handle /node2/* {  
        reverse_proxy mpc-node-2:6000  
      }  

      # Health check endpoint (optional)  
      handle /healthz {  
        respond "OK" 200  
      }  
    }