apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mpc-node
  name: mpc-node
spec:
  imagePullSecrets:
    - name: ghcr-secret  # Reference to the secret created
  containers:
    - name: mpc-node
      image: ghcr.io/venuswhispers/mpc-node-0:latest
      ports:
        - containerPort: 6000
          protocol: TCP
      env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "6000"
        - name: node_number
          value: "0"
        - name: sign_client_name
          value: gg18_sign_client
        - name: sign_sm_manager
          value: http://sm-manager:8000/
        - name: smTimeOutBound
          value: "3"
        # Update the database connection strings to use Cloud SQL Proxy
        - name: POSTGRESQL_URL
          value: postgres://lux:MNin08xAQ^.CT|<&@127.0.0.1:5432/mpc?sslmode=require
    - name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.17
      command: ["/cloud_sql_proxy", "-instances=lux-fi:europe-west2:luxdb=tcp:5432", "-credential_file=/secrets/cloudsql/key.json"]
      volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      ports:
        - containerPort: 5432  # Expose the port for the proxy
  restartPolicy: OnFailure
  volumes:
    - name: cloudsql-instance-credentials
      secret:
        secretName: cloudsql-instance-credentials