apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mpc-node-0
  name: mpc-node-0
spec:
  containers:
    - env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "6000"
        - name: node_number
          value: "0"
        - name: sign_client_name
          value: gg18_sign_client
        - name: sign_sm_manager
          value: http://sm-manager:8000/
        - name: smTimeOutBound
          value: "3"
      image: mpc_nodes_docker-mpc-node-0:latest
      name: mpc-node-0
      ports:
        - containerPort: 6000
          protocol: TCP
      imagePullPolicy: Never
  restartPolicy: OnFailure
