apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mpc-node-2
  name: mpc-node-2
spec:
  imagePullSecrets:
    - name: ghcr-secret  # Reference to the secret created
  containers:
    - env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "6000"
        - name: node_number
          value: "2"
        - name: sign_client_name
          value: gg18_sign_client
        - name: sign_sm_manager
          value: http://sm-manager:8000/
        - name: smTimeOutBound
          value: "3"
        - name: POSTGRES_PRISMA_URL
          value: postgres://default:5j6AXbyCRpJN@ep-solitary-river-a4wjo1ro-pooler.us-east-1.aws.neon.tech/verceldb?pgbouncer=true&connect_timeout=15&sslmode=require
        - name: POSTGRES_URL_NON_POOLING
          value: postgres://default:5j6AXbyCRpJN@ep-solitary-river-a4wjo1ro.us-east-1.aws.neon.tech/verceldb?sslmode=require
      image: ghcr.io/venuswhispers/mpc-node-2:latest
      name: mpc-node-2
      ports:
        - containerPort: 6000
          protocol: TCP
  restartPolicy: OnFailure
