apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mpc-node-1
  name: mpc-node-1
spec:
  type: NodePort
  ports:
    - name: "6001"
      port: 6001           # The port the service exposes inside the cluster
      targetPort: 6001     # The port on the container where your app is running
      nodePort: 30001      # The NodePort to expose externally (range 30000-32767)
      protocol: TCP
  selector:
    io.kompose.service: mpc-node-1
