apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sm-manager
  name: sm-manager
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000           # The port the service exposes inside the cluster
      targetPort: 8000     # The port on the container where your app is running
      protocol: TCP
  selector:
    io.kompose.service: sm-manager
