apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mpc-node-1
  name: mpc-node-1
spec:
  imagePullSecrets:
    - name: ghcr-secret  # Reference to the secret created
  containers:
    - env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "6000"
        - name: node_number
          value: "0"
        - name: sign_client_name
          value: gg18_sign_client
        - name: sign_sm_manager
          value: http://sm-manager:8000/
        - name: smTimeOutBound
          value: "3"
        - name: POSTGRESQL_URL
          value: postgresql://username:password@url?sslmode=require&sslcert=&sslkey=&sslrootcert=
      image: ghcr.io/venuswhispers/mpc-node-1:latest
      name: mpc-node-1
      ports:
        - containerPort: 6000
          protocol: TCP
      volumeMounts:
        - name: cloudsql-ssl-certs
          mountPath: /secrets/cloudsql
          readOnly: true
  restartPolicy: OnFailure
  volumes:
    - name: cloudsql-ssl-certs
      secret:
        secretName: cloudsql-ssl-certs
