export default {
  // Lux tokens
  LUX: ['ZLUX'],
  LBTC: ['WBTC', 'ZBTC', 'cbBTC'],
  LETH: ['ETH', 'WETH', 'ZETH'],
  LUSD: ['USDT', 'USDC', 'DAI', 'ZUSD'],
  LZOO: ['ZOO'],
  LBNB: ['BNB', 'ZBNB'],
  LPOL: ['POL', 'ZPOL'],
  LCELO: ['CELO', 'ZCELO'],
  LFTM: ['FTM', 'ZFTM'],
  LXDAI: ['XDAI', 'ZXDAI'],
  LSOL: ['ZSOL'],
  LTON: ['ZTON'],
  LADA: ['ZADA'],
  LAVAX: ['AVAX', 'ZAVAX'],
  LBLAST: ['ZBLAST', 'BLAST'],
  LBONK: ['ZBONK'],
  LWIF: ['ZWIF'],
  LPOPCAT: ['ZPOPCAT'],
  LPNUT: ['ZPNUT'],
  LMEW: ['ZMEW'],
  LBOME: ['ZBOME'],
  LGIGA: ['ZGIGA'],
  LAI16Z: ['ZAI16Z'],
  LFWOG: ['ZFWOG'],
  LMOODENG: ['ZMOODENG'],
  LPONKE: ['ZPONKE'],
  LNOT: ['ZNOT'],
  LDOGS: ['ZDOGS'],
  LMRB: ['ZMRB'],
  LREDO: ['ZREDO'],
  // Zoo tokens
  ZOO: ['LZOO'],
  ZBTC: ['WBTC', 'LBTC'],
  ZETH: ['ETH', 'WETH', 'LETH'],
  ZUSD: ['USDT', 'USDC', 'DAI', 'LUSD'],
  ZLUX: ['LUX'],
  ZBNB: ['BNB', 'LBNB'],
  ZPOL: ['POL', 'LPOL'],
  ZCELO: ['CELO', 'LCELO'],
  ZFTM: ['FTM', 'LFTM'],
  ZXDAI: ['XDAI', 'LXDAI'],
  ZSOL: ['LSOL'],
  ZTON: ['LTON'],
  ZADA: ['LADA'],
  ZAVAX: ['AVAX', 'LAVAX'],
  ZBLAST: ['LBLAST', 'BLAST'],
  ZBONK: ['LBONK'],
  ZWIF: ['LWIF'],
  ZPOPCAT: ['LPOPCAT'],
  ZPNUT: ['LPNUT'],
  ZMEW: ['LMEW'],
  ZBOME: ['LBOME'],
  ZGIGA: ['LGIGA'],
  ZAI16Z: ['LAI16Z'],
  ZFWOG: ['LFWOG'],
  ZMOODENG: ['LMOODENG'],
  ZPONKE: ['LPONKE'],
  ZNOT: ['LNOT'],
  ZDOGS: ['LDOGS'],
  ZMRB: ['LMRB'],
  ZREDO: ['LREDO'],
  // Evm tokens
  ETH: ['LETH', 'ZETH'],
  WETH: ['LETH', 'ZETH'],
  cbBTC: ['LBTC', 'ZBTC'],
  WBTC: ['LBTC', 'ZBTC'],
  POL: ['LPOL', 'ZPOL'],
  BNB: ['LBNB', 'ZBNB'],
  FTM: ['LFTM', 'ZFTM'],
  DAI: ['LUSD', 'ZUSD'],
  USDT: ['LUSD', 'ZUSD'],
  USDC: ['LUSD', 'ZUSD'],
  CELO: ['LCELO', 'ZCELO'],
  XDAI: ['LXDAI', 'ZXDAI'],
  AVAX: ['LAVAX', 'ZAVAX'],
  BLAST: ['LBLAST', 'ZBLAST'],
  //// Utila tokens
  BTC: ['LBTC', 'ZBTC'],
  TON: ['LTON', 'ZTON'],
  // Solana tokens
  SOL: ['LSOL', 'ZSOL'],
  BONK: ['LBONK', 'ZBONK'],
  SIXR: ['LSIXR', 'ZSIXR'],
  WIF: ['LWIF', 'ZWIF'],
  POPCAT: ['LPOPCAT', 'ZPOPCAT'],
  PNUT: ['LPNUT', 'ZPNUT'],
  MEW: ['LMEW', 'ZMEW'],
  BOME: ['LBOME', 'ZBOME'],
  GIGA: ['LGIGA', 'ZGIGA'],
  AI16Z: ['LAI16Z', 'ZAI16Z'],
  FWOG: ['LFWOG', 'ZFWOG'],
  MOODENG: ['LMOODENG', 'ZMOODENG'],
  PONKE: ['LPONKE', 'ZPONKE'],
  // Ton tokens
  NOT: ['LNOT', 'ZNOT'],
  DOGS: ['LDOGS', 'ZDOGS'],
  MRB: ['LMRB', 'ZMRB'],
  REDO: ['LREDO', 'ZREDO']
} satisfies Record<string, string[]> 
