import { type Network } from '@luxfi/core'

export default [
  {
    "display_name": "Ethereum Sepolia",
    "internal_name": "ETHEREUM_SEPOLIA",
    "logo": "https://cdn.lux.network/bridge/networks/ethereum_sepolia.png",
    "native_currency": "ETH",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:01:04.0494430",
    "chain_id": "11155111",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://sepolia.etherscan.io/tx/{0}",
    "account_explorer_template": "https://sepolia.etherscan.io/address/{0}",
    "currencies": [
      {
        "name": "ETH",
        "asset": "ETH",
        "logo": "https://cdn.lux.network/bridge/currencies/ethereum_eth.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "0x1a21E9c483200714489B575851e75d4C9525588E",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "0xE9FF4E487ffcA25a765D5445CC8665128Ac35820",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "0x299e04DE65090D3C48019893e369A7983124c514",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      },
      {
        "name": "DAI",
        "asset": "DAI",
        "logo": "https://cdn.lux.network/bridge/currencies/dai.png",
        "contract_address": "0x3FADaC51B852273e11Da42Db30714FddA785b8C5",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://old-green-glade.ethereum-sepolia.quiknode.pro/0523b575936957f0e7eae638096d19465aae8f8c/"]
  },
  {
    "display_name": "Base Sepolia",
    "internal_name": "BASE_SEPOLIA",
    "logo": "https://cdn.lux.network/bridge/networks/base_mainnet.png",
    "native_currency": "ETH",
    "is_testnet": true,
    "is_featured": false,
    "average_completion_time": "00:01:29.5988440",
    "chain_id": "84532",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://sepolia.basescan.org/tx/{0}",
    "account_explorer_template": "https://sepolia.basescan.org/address/{0}",
    "currencies": [
      {
        "name": "ETH",
        "asset": "ETH",
        "logo": "https://cdn.lux.network/bridge/currencies/ethereum_eth.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "0x7390C3FA8576a0E9E7c788cc7955c3151c4c1612",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "0x46390FA219b22f739C63F0bF1c165a1FBc30B57c",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "0xE49355609F94A4B8a2EfC6FBd077542F8EC90080",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      },
      {
        "name": "DAI",
        "asset": "DAI",
        "logo": "https://cdn.lux.network/bridge/currencies/dai.png",
        "contract_address": "0x568BF299E115D78a1fBa57BafdAe0fD8A26BFb7e",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://sepolia.base.org"
    ]
  },
  {
    "display_name": "Holesky Testnet",
    "internal_name": "HOLESKY_TESTNET",
    "logo": "https://cdn.lux.network/bridge/networks/holesky_testnet.png",
    "native_currency": "ETH",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:01:04.0494430",
    "chain_id": "17000",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://holesky.etherscan.io/tx/{0}",
    "account_explorer_template": "https://holesky.etherscan.io/address/{0}",
    "currencies": [
      {
        "name": "ETH",
        "asset": "ETH",
        "logo": "https://cdn.lux.network/bridge/currencies/ethereum_eth.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "0xcf963Fe4E4cE126047147661e6e06e171f366506",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "0xD257ADA332da217c78959A609e97c71ce5214925",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "0x15BA7dCA26c63029E33C81f7B3978B54Bc0CB08B",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      },
      {
        "name": "DAI",
        "asset": "DAI",
        "logo": "https://cdn.lux.network/bridge/currencies/dai.png",
        "contract_address": "0x9F47CeB09cb88362f0274Bb354a9807Fd976D963",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0.2,
        "withdrawal_fee": 0.2,
        "source_base_fee": 1,
        "destination_base_fee": 1,
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://ethereum-holesky-rpc.publicnode.com/"]
  },
  {
    "display_name": "Lux Testnet",
    "internal_name": "LUX_TESTNET",
    "logo": "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
    "native_currency": "LUX",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:00:07.7777777",
    "chain_id": "96368",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://explore.lux-test.network/tx/{0}",
    "account_explorer_template": "https://explore.lux-test.network/address/{0}",
    "currencies": [
      {
        "name": "LUX",
        "asset": "LUX",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lux.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "",
        "decimals": 6,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "",
        "decimals": 6,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "DAI",
        "asset": "DAI",
        "logo": "https://cdn.lux.network/bridge/currencies/dai.png",
        "contract_address": "",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Liquid BTC",
        "asset": "LBTC",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lbtc.svg",
        "contract_address": "0x1E48D32a4F5e9f08DB9aE4959163300FaF8A6C8e",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid ETH",
        "asset": "LETH",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/leth.svg",
        "contract_address": "0x60E0a8167FC13dE89348978860466C9ceC24B9ba",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid Dollar",
        "asset": "LUSD",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lusd.svg",
        "contract_address": "0x848Cff46eb323f323b6Bbe1Df274E40793d7f2c2",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid ZOO",
        "asset": "LZOO",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lzoo.svg",
        "contract_address": "0x5E5290f350352768bD2bfC59c2DA15DD04A7cB88",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid BNB",
        "asset": "LBNB",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lbnb.svg",
        "contract_address": "0x6EdcF3645DeF09DB45050638c41157D8B9FEa1cf",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid POL",
        "asset": "LPOL",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lpol.svg",
        "contract_address": "0x28BfC5DD4B7E15659e41190983e5fE3df1132bB9",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid CELO",
        "asset": "LCELO",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lcelo.svg",
        "contract_address": "0x3078847F879A33994cDa2Ec1540ca52b5E0eE2e5",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid FTM",
        "asset": "LFTM",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lftm.svg",
        "contract_address": "0x8B982132d639527E8a0eAAD385f97719af8f5e04",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid xDAI",
        "asset": "LXDAI",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lxdai.svg",
        "contract_address": "0x7dfb3cBf7CF9c96fd56e3601FBA50AF45C731211",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid SOL",
        "asset": "LSOL",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lsol.svg",
        "contract_address": "0x26B40f650156C7EbF9e087Dd0dca181Fe87625B7",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid TON",
        "asset": "LTON",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lton.svg",
        "contract_address": "0x3141b94b89691009b950c96e97Bff48e0C543E3C",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid ADA",
        "asset": "LADA",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lada.svg",
        "contract_address": "0x8b34152832b8ab4a3274915675754AA61eC113F0",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid AVAX",
        "asset": "LAVAX",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lavax.svg",
        "contract_address": "0x8fa9C0aeb525AF23b6A2e3f18a7d306280FD8C94",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid BLAST",
        "asset": "LBLAST",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lblast.svg",
        "contract_address": "0x86B52f1c726BCCcF1CC517AF4fB2983A9e978078",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid BONK",
        "asset": "LBONK",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lbonk.svg",
        "contract_address": "0xEa0Dd891Dd65b472a52cb48EbddA491612c8aE81",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid WIF",
        "asset": "LWIF",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lwif.svg",
        "contract_address": "0x0D15Fb059AE5DBb2826875591C450a2e59bFE9cA",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid Popcat",
        "asset": "LPOPCAT",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lpopcat.svg",
        "contract_address": "0xE48e3F2F82449c8A5d14E841d0db6544AA933552",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid PNUT",
        "asset": "LPNUT",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lpnut.svg",
        "contract_address": "0x6d5a2779313faa0CF50882D5338de19352267935",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid MEW",
        "asset": "LMEW",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lmew.svg",
        "contract_address": "0xf4Bf3d21C6F7559FDFc4Eaeeeb76f896884eC3bb",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid BOME",
        "asset": "LBOME",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lbome.svg",
        "contract_address": "0x1a08b4D4144027f8E262892A78D493dD660D270d",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid GIGA",
        "asset": "LGIGA",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lgiga.svg",
        "contract_address": "0x695249d2624A269bb04B948bb8ABB876b21Fd0B1",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid AI16Z",
        "asset": "LAI16Z",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lai16z.svg",
        "contract_address": "0x475b2846FfcfCF66294B5A829ee44dE4aBDdFf12",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid FWOG",
        "asset": "LFWOG",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lfwog.svg",
        "contract_address": "0xA83bCcd4542f6d27ad3698f5311265D87910b72a",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid MOODENG",
        "asset": "LMOODENG",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lmoodeng.svg",
        "contract_address": "0xf8a40f7209032037C719Ab5EA7Ad12643F258787",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Liquid PONKE",
        "asset": "LPONKE",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lponke.svg",
        "contract_address": "0x40cbF49487F30082A233A73759cAE283F81113AE",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://api.lux-test.network"]
  },
  {
    "display_name": "Zoo Testnet",
    "internal_name": "ZOO_TESTNET",
    "logo": "https://cdn.lux.network/bridge/networks/zoo_mainnet.svg",
    "native_currency": "ZOO",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:00:07.7777777",
    "chain_id": "200201",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://explore.zoo-test.network/tx/{0}",
    "account_explorer_template": "https://explore.zoo-test.network/address/{0}",
    "currencies": [
      {
        "name": "ZOO",
        "asset": "ZOO",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "",
        "decimals": 6,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "",
        "decimals": 6,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "DAI",
        "asset": "DAI",
        "logo": "https://cdn.lux.network/bridge/currencies/dai.png",
        "contract_address": "",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Zoo BTC",
        "asset": "ZBTC",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zbtc.svg",
        "contract_address": "0x1E48D32a4F5e9f08DB9aE4959163300FaF8A6C8e",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo ETH",
        "asset": "ZETH",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zeth.svg",
        "contract_address": "0x60E0a8167FC13dE89348978860466C9ceC24B9ba",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo Dollar",
        "asset": "ZUSD",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zusd.svg",
        "contract_address": "0x848Cff46eb323f323b6Bbe1Df274E40793d7f2c2",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo LUX",
        "asset": "ZLUX",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zlux.svg",
        "contract_address": "0x5E5290f350352768bD2bfC59c2DA15DD04A7cB88",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo BNB",
        "asset": "ZBNB",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zbnb.svg",
        "contract_address": "0x6EdcF3645DeF09DB45050638c41157D8B9FEa1cf",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo POL",
        "asset": "ZPOL",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zpol.svg",
        "contract_address": "0x28BfC5DD4B7E15659e41190983e5fE3df1132bB9",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo CELO",
        "asset": "ZCELO",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zcelo.svg",
        "contract_address": "0x3078847F879A33994cDa2Ec1540ca52b5E0eE2e5",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo FTM",
        "asset": "ZFTM",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zftm.svg",
        "contract_address": "0x8B982132d639527E8a0eAAD385f97719af8f5e04",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo xDAI",
        "asset": "ZXDAI",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zxdai.svg",
        "contract_address": "0x7dfb3cBf7CF9c96fd56e3601FBA50AF45C731211",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo SOL",
        "asset": "ZSOL",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zsol.svg",
        "contract_address": "0x26B40f650156C7EbF9e087Dd0dca181Fe87625B7",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo TON",
        "asset": "ZTON",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zton.svg",
        "contract_address": "0x3141b94b89691009b950c96e97Bff48e0C543E3C",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo ADA",
        "asset": "ZADA",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zada.svg",
        "contract_address": "0x8b34152832b8ab4a3274915675754AA61eC113F0",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo AVAX",
        "asset": "ZAVAX",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zavax.svg",
        "contract_address": "0x8fa9C0aeb525AF23b6A2e3f18a7d306280FD8C94",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo BLAST",
        "asset": "ZBLAST",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zblast.svg",
        "contract_address": "0x86B52f1c726BCCcF1CC517AF4fB2983A9e978078",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo BONK",
        "asset": "ZBONK",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zbonk.svg",
        "contract_address": "0xEa0Dd891Dd65b472a52cb48EbddA491612c8aE81",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo WIF",
        "asset": "ZWIF",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zwif.svg",
        "contract_address": "0x0D15Fb059AE5DBb2826875591C450a2e59bFE9cA",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo Popcat",
        "asset": "ZPOPCAT",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zpopcat.svg",
        "contract_address": "0xE48e3F2F82449c8A5d14E841d0db6544AA933552",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo PNUT",
        "asset": "ZPNUT",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zpnut.svg",
        "contract_address": "0x6d5a2779313faa0CF50882D5338de19352267935",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo MEW",
        "asset": "ZMEW",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zmew.svg",
        "contract_address": "0xf4Bf3d21C6F7559FDFc4Eaeeeb76f896884eC3bb",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo BOME",
        "asset": "ZBOME",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zbome.svg",
        "contract_address": "0x1a08b4D4144027f8E262892A78D493dD660D270d",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo GIGA",
        "asset": "ZGIGA",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zgiga.svg",
        "contract_address": "0x695249d2624A269bb04B948bb8ABB876b21Fd0B1",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo AI16Z",
        "asset": "ZAI16Z",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zai16z.svg",
        "contract_address": "0x475b2846FfcfCF66294B5A829ee44dE4aBDdFf12",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo FWOG",
        "asset": "ZFWOG",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zfwog.svg",
        "contract_address": "0xA83bCcd4542f6d27ad3698f5311265D87910b72a",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo MOODENG",
        "asset": "ZMOODENG",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zmoodeng.svg",
        "contract_address": "0xf8a40f7209032037C719Ab5EA7Ad12643F258787",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      },
      {
        "name": "Zoo PONKE",
        "asset": "ZPONKE",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zponke.svg",
        "contract_address": "0x40cbF49487F30082A233A73759cAE283F81113AE",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 1,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0, 
        "mint": true
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://api.zoo-test.network"]
  },
  {
    "display_name": "BSC Testnet",
    "internal_name": "BSC_TESTNET",
    "logo": "https://cdn.lux.network/bridge/networks/bsc_mainnet.png",
    "native_currency": "BNB",
    "is_testnet": true,
    "is_featured": false,
    "average_completion_time": "00:01:26.4349620",
    "chain_id": "97",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://testnet.bscscan.com/tx/{0}",
    "account_explorer_template": "https://testnet.bscscan.com/address/{0}",
    "currencies": [
      {
        "name": "BNB",
        "asset": "BNB",
        "logo": "https://cdn.lux.network/bridge/networks/bsc_mainnet.png",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "0xA5fec41B6B2C98dd6036df4030396C947aFe1AcB",
        "decimals": 18,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "0x5519582dde6eb1f53F92298622c2ecb39A64369A",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "0x6a49DbeD52B9Bd9a53E21C3bCb67dc2697cD6697",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "DAI",
        "asset": "DAI",
        "logo": "https://cdn.lux.network/bridge/currencies/dai.png",
        "contract_address": "0x2E8A24dE21105772FD161BF56471A0470A8AF45e",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://data-seed-prebsc-1-s1.bnbchain.org:8545"]
  },
  {
    "display_name": "Bitcoin Testnet",
    "internal_name": "BITCOIN_TESTNET",
    "logo": "https://cdn.lux.network/bridge/networks/bitcoin_mainnet.png",
    "native_currency": "BTC",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:04:39.5276290",
    "chain_id": null,
    "status": "active",
    "type": "btc",
    "transaction_explorer_template": "https://blockstream.info/testnet/tx/{0}",
    "account_explorer_template": "https://blockstream.info/testnet/address/{0}",
    "currencies": [
      {
        "name": "BTC",
        "asset": "BTC",
        "logo": "https://cdn.lux.network/bridge/currencies/btc.svg",
        "contract_address": null,
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      }
    ],
    "metadata": null,
    "managed_accounts": ["UQAvirnJ3tWyhjU0At4qRr-Miph3bI_38vgp0h73SHTl3TDB"],
    "nodes": []
  },
  {
    "display_name": "Solana Devnet",
    "internal_name": "SOLANA_DEVNET",
    "logo": "https://cdn.lux.network/bridge/networks/solana_devnet.png",
    "native_currency": "SOL",
    "is_testnet": true,
    "is_featured": false,
    "average_completion_time": "00:03:07.9874770",
    "chain_id": null,
    "status": "active",
    "type": "solana",
    "transaction_explorer_template": "https://explorer.solana.com/?cluster=devnet/tx/{0}",
    "account_explorer_template": "https://explorer.solana.com/?cluster=devnet/address/{0}",
    "currencies": [
      {
        "name": "SOL",
        "asset": "SOL",
        "logo": "https://cdn.lux.network/bridge/currencies/sol.png",
        "contract_address": null,
        "decimals": 9,
        "status": "active",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0.01,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      }
    ],
    "metadata": null,
    "managed_accounts": ["2ZUoHEPcN7bsSXw6YTj85CMrU8xNtcYNGiSMXPLomaa2"],
    "nodes": ["https://api.testnet.solana.com"]
  },
  {
    "display_name": "Ton",
    "internal_name": "TON_TESTNET",
    "logo": "https://cdn.lux.network/bridge/networks/ton_mainnet.svg",
    "native_currency": "TON",
    "is_testnet": true,
    "is_featured": false,
    "average_completion_time": "00:04:39.5276290",
    "chain_id": null,
    "status": "inactive",
    "type": "ton",
    "transaction_explorer_template": "https://tonscan.org/tx/{0}",
    "account_explorer_template": "https://tonscan.org/address/{0}",
    "currencies": [
      {
        "name": "TON",
        "asset": "TON",
        "logo": "https://cdn.lux.network/bridge/currencies/ton.svg",
        "contract_address": null,
        "decimals": 9,
        "status": "inactive",
        "is_deposit_enabled": false,
        "is_withdrawal_enabled": false,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      }
    ],
    "metadata": null,
    "managed_accounts": ["UQAvirnJ3tWyhjU0At4qRr-Miph3bI_38vgp0h73SHTl3TDB"],
    "nodes": []
  }
] satisfies Network[]
