apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bridge-server
  name: bridge-server
spec:
  imagePullSecrets:
    - name: ghcr-secret # Reference to the secret created
  containers:
    - name: bridge-server # Container name should be specified here within the container list
      image: ghcr.io/luxfi/bridge/server:latest
      env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "6000"
        - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: bridge-server-secret
                  key: POSTGRES_URL
      ports:
        - containerPort: 6000
          protocol: TCP
  restartPolicy: OnFailure
