apiVersion: v1
kind: Service
metadata:
  name: bridge-service
  labels:
    app: bridge-server
spec:
  type: NodePort
  ports:
    - name: "6000"
      port: 6000
      targetPort: 6000
      protocol: TCP
      nodePort: 30005
  selector:
    app: bridge-server
