services:
  bridge-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=
      - POSTGRES_URL=
      - COINBASE_API_KEY=
      - LUX_SIGNER=
      - SERVICE_ACCOUNT_EMAIL=
      - SERVICE_ACCOUNT_PRIVATE_KEY=
    ports:
      - "6000:6000"
    networks:
      - lux-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  lux-network:
    driver: bridge
