import { type Network } from '@luxfi/core'

export default [
  {
    "display_name": "Lux Devnet",
    "internal_name": "LUX_DEVNET",
    "logo": "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
    "native_currency": "LUX",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:00:03.0000000",
    "chain_id": "96370",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://explore-dev.lux.network/tx/{0}",
    "account_explorer_template": "https://explore-dev.lux.network/address/{0}",
    "currencies": [
      {
        "name": "LUX",
        "asset": "LUX",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lux.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Liquid BTC",
        "asset": "LBTC",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lbtc.svg",
        "contract_address": "",
        "decimals": 8,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Liquid ETH",
        "asset": "LETH",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/leth.svg",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Liquid USD",
        "asset": "LUSD",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lusd.svg",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Liquid ZOO",
        "asset": "LZOO",
        "logo": "https://cdn.lux.network/bridge/currencies/lux/lzoo.svg",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://api.lux-dev.network"]
  },
  {
    "display_name": "Zoo Devnet",
    "internal_name": "ZOO_DEVNET",
    "logo": "https://cdn.lux.network/bridge/networks/zoo_mainnet.svg",
    "native_currency": "ZOO",
    "is_testnet": true,
    "is_featured": true,
    "average_completion_time": "00:00:03.0000000",
    "chain_id": "200202",
    "status": "active",
    "type": "evm",
    "transaction_explorer_template": "https://explore-dev.lux.network/zoo/tx/{0}",
    "account_explorer_template": "https://explore-dev.lux.network/zoo/address/{0}",
    "currencies": [
      {
        "name": "ZOO",
        "asset": "ZOO",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo.svg",
        "contract_address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0
      },
      {
        "name": "WETH",
        "asset": "WETH",
        "logo": "https://cdn.lux.network/bridge/currencies/weth.png",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDT",
        "asset": "USDT",
        "logo": "https://cdn.lux.network/bridge/currencies/usdt.png",
        "contract_address": "",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "USDC",
        "asset": "USDC",
        "logo": "https://cdn.lux.network/bridge/currencies/usdc.png",
        "contract_address": "",
        "decimals": 6,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Zoo BTC",
        "asset": "ZBTC",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zbtc.svg",
        "contract_address": "",
        "decimals": 8,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Zoo ETH",
        "asset": "ZETH",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zeth.svg",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Zoo USD",
        "asset": "ZUSD",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zusd.svg",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      },
      {
        "name": "Zoo LUX",
        "asset": "ZLUX",
        "logo": "https://cdn.lux.network/bridge/currencies/zoo/zlux.svg",
        "contract_address": "",
        "decimals": 18,
        "status": "active",
        "is_deposit_enabled": true,
        "is_withdrawal_enabled": true,
        "is_refuel_enabled": false,
        "max_withdrawal_amount": 0,
        "deposit_fee": 0,
        "withdrawal_fee": 0,
        "source_base_fee": 0,
        "destination_base_fee": 0,
      }
    ],
    "metadata": null,
    "managed_accounts": [],
    "nodes": ["https://api.lux-dev.network"]
  }
] satisfies Network[]
