import { type Network } from "@/types/fireblocks";
const sourceNetworks: Network[] = [
  {
    display_name: "Bitcoin Testnet",
    internal_name: "BITCOIN_TESTNET",
    native_currency: "BTC",
    logo: "https://cdn.lux.network/bridge/networks/bitcoin_mainnet.png",
    is_testnet: true,
    is_featured: true,
    average_completion_time: "00:04:39.5276290",
    chain_id: null,
    status: "active",
    type: "btc",
    deposit_address: {
      address: "tb1qgps3lt0lz3mufdnmj3lhcnpfh48s2u53996xdv",
    },
    refuel_amount_in_usd: 1,
    transaction_explorer_template: "https://blockstream.info/testnet/tx/{0}",
    account_explorer_template: "https://blockstream.info/testnet/address/{0}",
    node: "",
    currencies: [
      {
        name: "BTC",
        asset: "BTC",
        contract_address: "",
        logo: "https://cdn.lux.network/bridge/currencies/btc.png",
        decimals: 8,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: false,
        is_refuel_enabled: false,
        max_withdrawal_amount: 0,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
    ],
  },
  {
    display_name: "Ethereum Sepolia",
    internal_name: "ETHEREUM_SEPOLIA",
    native_currency: "ETH",
    logo: "https://cdn.lux.network/bridge/networks/ethereum_sepolia.png",
    is_testnet: true,
    is_featured: true,
    average_completion_time: "00:01:04.0494430",
    chain_id: 11155111,
    status: "active",
    type: "evm",
    deposit_address: {
      address: "0xD4952A4c2644469D59F9dE340E0e829e51836Dec",
    },
    refuel_amount_in_usd: 0.5,
    transaction_explorer_template: "https://sepolia.etherscan.io/tx/{0}",
    account_explorer_template: "https://sepolia.etherscan.io/address/{0}",
    node: "https://old-green-glade.ethereum-sepolia.quiknode.pro/0523b575936957f0e7eae638096d19465aae8f8c/",
    currencies: [
      {
        name: "ETH",
        asset: "ETH",
        logo: "https://cdn.lux.network/bridge/currencies/ethereum_eth.svg",
        contract_address: "0x0000000000000000000000000000000000000000",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
      {
        name: "USDT",
        asset: "USDT",
        logo: "https://cdn.lux.network/bridge/currencies/usdt.png",
        contract_address: "0xE9FF4E487ffcA25a765D5445CC8665128Ac35820",
        decimals: 6,
        status: "inactive",
        is_deposit_enabled: false,
        is_withdrawal_enabled: false,
        is_refuel_enabled: false,
        max_withdrawal_amount: 0,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 1,
        destination_base_fee: 1,
        is_native: false,
      },
      {
        name: "USDC",
        asset: "USDC",
        logo: "https://cdn.lux.network/bridge/currencies/usdc.png",
        contract_address: "0x299e04DE65090D3C48019893e369A7983124c514",
        decimals: 6,
        status: "inactive",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: true,
        max_withdrawal_amount: 3000,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "DAI",
        asset: "DAI",
        logo: "https://cdn.lux.network/bridge/currencies/dai.png",
        contract_address: "0x3FADaC51B852273e11Da42Db30714FddA785b8C5",
        decimals: 18,
        status: "inactive",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: true,
        max_withdrawal_amount: 3000,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
    ],
  },
  {
    display_name: "Base Sepolia",
    internal_name: "BASE_SEPOLIA",
    native_currency: "ETH",
    logo: "https://cdn.lux.network/bridge/networks/base_mainnet.png",
    is_testnet: true,
    is_featured: true,
    average_completion_time: "00:01:04.0494430",
    chain_id: 84532, //base sepolia
    status: "active",
    type: "evm",
    deposit_address: {
      address: "0xD4952A4c2644469D59F9dE340E0e829e51836Dec",
    },
    refuel_amount_in_usd: 0.5,
    transaction_explorer_template: "https://sepolia.basescan.org/tx/{0}", // sepolia
    account_explorer_template: "https://sepolia.basescan.org/address/{0}", // sepolia
    node: "https://sepolia.base.org", // sepolia
    currencies: [
      {
        name: "ETH",
        asset: "ETH",
        logo: "https://cdn.lux.network/bridge/currencies/ethereum_eth.svg",
        contract_address: "0x0000000000000000000000000000000000000000",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
      {
        name: "USDT",
        asset: "USDT",
        logo: "https://cdn.lux.network/bridge/currencies/usdt.png",
        contract_address: "0x46390FA219b22f739C63F0bF1c165a1FBc30B57c",
        decimals: 6,
        status: "inactive",
        is_deposit_enabled: false,
        is_withdrawal_enabled: false,
        is_refuel_enabled: false,
        max_withdrawal_amount: 0,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "USDC",
        asset: "USDC",
        logo: "https://cdn.lux.network/bridge/currencies/usdc.png",
        contract_address: "0xE49355609F94A4B8a2EfC6FBd077542F8EC90080", //sepolia
        decimals: 6,
        status: "inactive",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: true,
        max_withdrawal_amount: 3000,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "DAI",
        asset: "DAI",
        logo: "https://cdn.lux.network/bridge/currencies/dai.png",
        contract_address: "0x568BF299E115D78a1fBa57BafdAe0fD8A26BFb7e",
        decimals: 18,
        status: "inactive",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: true,
        max_withdrawal_amount: 3000,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
    ],
  },
  {
    display_name: "Solana Testnet",
    internal_name: "SOLANA_TESTNET",
    native_currency: "SOL",
    logo: "https://cdn.lux.network/bridge/networks/solana_mainnet.png",
    is_testnet: true,
    is_featured: false,
    average_completion_time: "00:03:07.9874770",
    chain_id: null,
    status: "active",
    type: "solana",
    deposit_address: {
      address: "DsBiAAy92HtjXKFf78ZTQKCaMDuMGyUeh6v7pPSHrVbY",
    },
    refuel_amount_in_usd: 1,
    transaction_explorer_template:
      "https://explorer.solana.com/?cluster=testnet/tx/{0}",
    account_explorer_template:
      "https://explorer.solana.com/?cluster=testnet/address/{0}",
    node: "https://api.testnet.solana.com",
    currencies: [
      {
        name: "SOL",
        asset: "SOL",
        contract_address: null,
        logo: "https://cdn.lux.network/bridge/currencies/sol.png",
        decimals: 9,
        status: "active",
        is_deposit_enabled: false,
        is_withdrawal_enabled: false,
        is_refuel_enabled: false,
        max_withdrawal_amount: 0,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
    ],
  },
  {
    display_name: "Solana Devnet",
    internal_name: "SOLANA_DEVNET",
    native_currency: "SOL",
    logo: "https://cdn.lux.network/bridge/networks/solana_mainnet.png",
    is_testnet: true,
    is_featured: false,
    average_completion_time: "00:03:07.9874770",
    chain_id: null,
    status: "active",
    type: "solana",
    deposit_address: {
      address: "DsBiAAy92HtjXKFf78ZTQKCaMDuMGyUeh6v7pPSHrVbY",
    },
    refuel_amount_in_usd: 1,
    transaction_explorer_template:
      "https://explorer.solana.com/?cluster=testnet/tx/{0}",
    account_explorer_template:
      "https://explorer.solana.com/?cluster=testnet/address/{0}",
    node: "https://api.testnet.solana.com",
    currencies: [
      {
        name: "SOL",
        asset: "SOL",
        contract_address: null,
        logo: "https://cdn.lux.network/bridge/currencies/sol.png",
        decimals: 9,
        status: "active",
        is_deposit_enabled: false,
        is_withdrawal_enabled: false,
        is_refuel_enabled: false,
        max_withdrawal_amount: 0,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
    ],
  },
  {
    display_name: "Ton Testnet",
    internal_name: "TON_TESTNET",
    native_currency: "TON",
    logo: "https://cdn.lux.network/bridge/networks/ton_mainnet.svg",
    is_testnet: false,
    is_featured: false,
    average_completion_time: "00:04:39.5276290",
    chain_id: null,
    status: "active",
    type: "ton",
    deposit_address: {
      address: "0QDMXrj5n4ldLGoq9l0svifDORdTLnKsOEH6ClAEXX5qj1Sq",
      memo: "70A09E871BFAFCB0A216",
    },
    refuel_amount_in_usd: 1,
    transaction_explorer_template: "https://tonscan.org/tx/{0}",
    account_explorer_template: "https://tonscan.org/address/{0}",
    node: "UQAvirnJ3tWyhjU0At4qRr-Miph3bI_38vgp0h73SHTl3TDB",
    currencies: [
      {
        name: "TON",
        asset: "TON",
        contract_address: null,
        logo: "https://cdn.lux.network/bridge/currencies/ton.svg",
        decimals: 9,
        status: "active",
        is_deposit_enabled: false,
        is_withdrawal_enabled: false,
        is_refuel_enabled: false,
        max_withdrawal_amount: 0,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
      {
        name: "jUSDC",
        asset: "jUSDC",
        contract_address: "EQB-MPwrd1G6WKNkLz_VnV6WqBDd142KMQv-g1O-8QUA3728",
        logo: "https://cdn.lux.network/bridge/currencies/usdc.png",
        decimals: 6,
        status: "inactive",
        is_deposit_enabled: false,
        is_withdrawal_enabled: true,
        is_refuel_enabled: true,
        max_withdrawal_amount: 500,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
    ],
  },
];
const destinationNetworks: Network[] = [
  {
    display_name: "Lux Testnet",
    internal_name: "LUX_TESTNET",
    native_currency: "LUX",
    logo: "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
    is_testnet: false,
    is_featured: true,
    average_completion_time: "00:00:07.7777777",
    chain_id: 7777,
    status: "active",
    type: "evm",
    refuel_amount_in_usd: 1,
    transaction_explorer_template: "https://explore.lux-test.network/tx/{0}",
    account_explorer_template: "https://explore.lux-test.network/address/{0}",
    node: "https://api.lux-test.network",
    currencies: [
      {
        name: "LUX",
        asset: "LUX",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lux.svg",
        contract_address: "0x0000000000000000000000000000000000000000",
        decimals: 18,
        status: "inactive",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: true,
      },
      {
        name: "Lux BTC",
        asset: "LBTC",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lbtc.svg",
        contract_address: "0xebD1Ee9BCAaeE50085077651c1a2dD452fc6b72e",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux ETH",
        asset: "LETH",
        logo: "https://cdn.lux.network/bridge/currencies/lux/leth.svg",
        contract_address: "0x2951A9386df11a4EA8ae5A823B94DC257dEb35Cb",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux POL",
        asset: "LPOL",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lpol.svg",
        contract_address: "0x9F47CeB09cb88362f0274Bb354a9807Fd976D963",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux BNB",
        asset: "LBNB",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lbnb.svg",
        contract_address: "0xcf963Fe4E4cE126047147661e6e06e171f366506",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux FTM",
        asset: "LFTM",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lftm.svg",
        contract_address: "0x15BA7dCA26c63029E33C81f7B3978B54Bc0CB08B",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux CELO",
        asset: "LCELO",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lcelo.svg",
        contract_address: "0xD257ADA332da217c78959A609e97c71ce5214925",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux xDAI",
        asset: "LXDAI",
        logo: "https://cdn.lux.network/bridge/currencies/lux/ldai.svg",
        contract_address: "0x0D15251ad56cE56cC22588F6645c20ee7d77aE39",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux SOL",
        asset: "LSOL",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lsol.svg",
        contract_address: "0x372b3B7Cb87A7aE9Cb024861775f01015A71058C",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux TON",
        asset: "LTON",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lton.svg",
        contract_address: "0xa4AA40ff2F2Cbe4FFcDfa5fF2A466fa7aF3390e5",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
      {
        name: "Lux Dollar",
        asset: "LUSD",
        logo: "https://cdn.lux.network/bridge/currencies/lux/lusd.svg",
        contract_address: "0x42b733cA4b3A8FC0237dBE39A47441cfD525f0F1",
        decimals: 18,
        status: "active",
        is_deposit_enabled: true,
        is_withdrawal_enabled: true,
        is_refuel_enabled: false,
        max_withdrawal_amount: 1,
        deposit_fee: 0.1,
        withdrawal_fee: 0.1,
        source_base_fee: 0.1,
        destination_base_fee: 0.1,
        is_native: false,
      },
    ],
  },
];
export default { sourceNetworks, destinationNetworks };
