export enum Networks {
  BitcoinMainnet = 'networks/bitcoin-mainnet',
  BitcoinTestnet = 'networks/bitcoin-testnet',
  EthereumMainnet = 'networks/ethereum-mainnet',
  EthereumTestnetGoerli = 'networks/ethereum-testnet-goerli',
  EthereumTestnetSepolia = 'networks/ethereum-testnet-sepolia',
  OptimismMainnet = 'networks/optimism-mainnet',
  OptimismTestnetGoerli = 'networks/optimism-testnet-goerli',
  PolygonMainnet = 'networks/polygon-mainnet',
  PolygonTestnetMumbai = 'networks/polygon-testnet-mumbai',
  PolygonTestnetAmoy = 'networks/polygon-testnet-amoy',
  ArbitrumMainnet = 'networks/arbitrum-mainnet',
  ArbitrumTestnetGoerli = 'networks/arbitrum-testnet-goerli',
  AvalancheCChainMainnet = 'networks/avalanche-c-chain-mainnet',
  AvalancheCChainTestnetFuji = 'networks/avalanche-c-chain-testnet-fuji',
  BinanceSmartChainMainnet = 'networks/bnb-smart-chain-mainnet',
  BinanceSmartChainTestnet = 'networks/bnb-smart-chain-testnet',
  FuseMainnet = 'networks/fuse-mainnet',
  FuseTestnetSpark = 'networks/fuse-testnet-spark',
  BaseMainnet = 'networks/base-mainnet',
  BaseTestnetGoerli = 'networks/base-testnet-goerli',
  TronMainnet = 'networks/tron-mainnet',
  SolanaMainnet = 'networks/solana-mainnet',
  SolanaDevnet = 'networks/solana-devnet',
  TonMainnet = 'networks/ton-mainnet',
  TronTestnet = 'networks/tron-testnet-shasta',
  CosmosHubMainnet = 'networks/cosmoshub-mainnet',
}
