name: Docker Image CI for GHCR for Bridge Backend
on:
  push:
    branches:
      - main
    paths:
      - "apps/bridge/backend**" # Only trigger the workflow for changes in the apps/bridge/backend subfoler
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        run: |
          docker login --username venuswhispers --password ${{ secrets.GH_PAT }} ghcr.io
      - name: Build and push Docker images
        run: |
          cd mpc-nodes/docker  # Navigate to the subfolder containing the Docker project
          cd apps/bridge/backend
          docker build -f Dockerfile -t ghcr.io/luxfi/bridge/backend:latest .  
          docker push ghcr.io/luxfi/bridge/backend:latest
