name: Docker Image CI for GHCR for MPC-Nodes
on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:  
          node-version: '20'  # Ensure checkout action runs on Node.js 20 
      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2
        with:  
          node-version: '20'  # Ensure Buildx action runs on Node.js 20  
      - name: Log in to GitHub Container Registry
        run : |  
          docker login --username venuswhispers --password ${{ secrets.GH_PAT }} ghcr.io
      - name: Build and push Docker images
        run: | 
          cd mpc-nodes  # Navigate to the subfolder containing the Docker project  
          docker compose build  # Build the services defined in compose.yaml  
          docker compose push # Push the built images to GHCR