name: MPC Tests [DEPRECATED]

on:
  workflow_dispatch:  # Only manual trigger since mpc-service directory is removed

jobs:
  deprecated_notice:
    name: Deprecation Notice
    runs-on: ubuntu-latest
    
    steps:
    - name: MPC Tests Deprecated
      run: |
        echo "This workflow is deprecated."
        echo "The mpc-service directory has been removed."
        echo "MPC functionality has been migrated to native Go integration."
        echo "Use the MPC E2E Tests workflow instead."
        exit 0