name: mpc-nodes [DEPRECATED]
on:
  workflow_dispatch:  # Only manual trigger since mpc-nodes directory is removed
jobs:
  deprecated_notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "This workflow is deprecated."
          echo "MPC functionality has been migrated to native Go integration."
          echo "See docs/MPC-GO-INTEGRATION.md for details."
          exit 0
