import { Network } from "@/types/teleport";

export const sourceNetworks: Network[] = [
    {
        display_name: "Ethereum",
        internal_name: "ETHEREUM_MAINNET",
        native_currency: "ETH",
        logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
        is_testnet: false,
        is_featured: true,
        average_completion_time: "00:01:04.0494430",
        chain_id: 11155111, //sepolia
        status: "active",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://sepolia.etherscan.io/tx/{0}", // sepolia
        account_explorer_template: "https://sepolia.etherscan.io/address/{0}", // sepolia
        node: "https://sepolia.infura.io/v3/2e58a899d3c64eccb6955c2f33fc8a88", // sepolia
        currencies: [
            {
                name: "ETH",
                asset: "ETH",
                logo: "https://cdn.lux.network/bridge/currencies/eth.png",
                contract_address: null,
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: true
            },
            {
                name: "BKT",
                asset: "BKT",
                logo: "https://cdn.lux.network/bridge/currencies/bkt.png",
                contract_address: "0x9d62526f5Ce701950c30F2cACa70Edf70f9fbf0F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ASTR",
                asset: "ASTR",
                logo: "https://cdn.lux.network/bridge/currencies/astr.png",
                contract_address: "0x9bBAf650DcD8D3583195715Fc46b1118c3CfDdfd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ZKS",
                asset: "ZKS",
                logo: "https://cdn.lux.network/bridge/currencies/zks.png",
                contract_address: "0xe4815AE53B124e7263F08dcDBBB757d41Ed658c6",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 10000,
                deposit_fee: 166.865654,
                withdrawal_fee: 65.820981,
                source_base_fee: 26.053974,
                destination_base_fee: 26.053974,
                is_native: false
            },
            {
                name: "USDT",
                asset: "USDT",
                logo: "https://cdn.lux.network/bridge/currencies/usdt.png",
                contract_address: "0xa92E09451140d645A2fE262c9631Dd808439dDEd",// sepolia
                decimals: 6,
                status: "active",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 4.68,
                withdrawal_fee: 2.24,
                source_base_fee: 1,
                destination_base_fee: 1,
                is_native: false
            },
            {
                name: "USDC",
                asset: "USDC",
                logo: "https://cdn.lux.network/bridge/currencies/usdc.png",
                contract_address: "0xB587bAb3d507d720625D30544C2889D661446BF7",//sepolia
                decimals: 6,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 3000,
                deposit_fee: 12.79,
                withdrawal_fee: 6.4,
                source_base_fee: 0.99,
                destination_base_fee: 0.99,
                is_native: false
            },
            {
                name: "DAI",
                asset: "DAI",
                logo: "https://cdn.lux.network/bridge/currencies/dai.png",
                contract_address: "0x7390C3FA8576a0E9E7c788cc7955c3151c4c1612",
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 3000,
                deposit_fee: 12.79,
                withdrawal_fee: 6.4,
                source_base_fee: 0.99,
                destination_base_fee: 0.99,
                is_native: false
            },
            {
                name: "LRC",
                asset: "LRC",
                logo: "https://cdn.lux.network/bridge/currencies/lrc.png",
                contract_address: "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 10000,
                deposit_fee: 52.455252,
                withdrawal_fee: 21.830179,
                source_base_fee: 4.435022,
                destination_base_fee: 4.435022,
                is_native: false
            },
            {
                name: "IMX",
                asset: "IMX",
                logo: "https://cdn.lux.network/bridge/currencies/imx.png",
                contract_address: "0xF57e7e7C23978C3cAEC3C3548E3D615c346e79fF",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 500,
                deposit_fee: 6.377331,
                withdrawal_fee: 2.65567,
                source_base_fee: 0.555555,
                destination_base_fee: 0.555555,
                is_native: false
            },
            {
                name: "SNX",
                asset: "SNX",
                logo: "https://cdn.lux.network/bridge/currencies/snx.png",
                contract_address: "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 500,
                deposit_fee: 6.676014,
                withdrawal_fee: 4.652934,
                source_base_fee: 0.316455,
                destination_base_fee: 0.316455,
                is_native: false
            }
        ]
    },
    {
        display_name: "Binance Smart Chain",
        internal_name: "BSC_MAINNET",
        native_currency: "BNB",
        logo: "https://cdn.lux.network/bridge/networks/bsc_mainnet.png",
        is_testnet: false,
        is_featured: false,
        average_completion_time: "00:01:04.0494430",
        chain_id: 56,
        status: "inactive",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: [
            {
                name: "BNB",
                asset: "BNB",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: null,
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: true
            },
            {
                name: "BKT",
                asset: "BKT",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0x9d62526f5Ce701950c30F2cACa70Edf70f9fbf0F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ASTR",
                asset: "ASTR",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0x9bBAf650DcD8D3583195715Fc46b1118c3CfDdfd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ZKS",
                asset: "ZKS",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xe4815AE53B124e7263F08dcDBBB757d41Ed658c6",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 10000,
                deposit_fee: 166.865654,
                withdrawal_fee: 65.820981,
                source_base_fee: 26.053974,
                destination_base_fee: 26.053974,
                is_native: false
            },
            {
                name: "USDT",
                asset: "USDT",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
                decimals: 6,
                status: "active",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 4.68,
                withdrawal_fee: 2.24,
                source_base_fee: 1,
                destination_base_fee: 1,
                is_native: false
            },
            {
                name: "USDC",
                asset: "USDC",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                decimals: 6,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 3000,
                deposit_fee: 12.79,
                withdrawal_fee: 6.4,
                source_base_fee: 0.99,
                destination_base_fee: 0.99,
                is_native: false
            },

            {
                name: "LRC",
                asset: "LRC",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 10000,
                deposit_fee: 52.455252,
                withdrawal_fee: 21.830179,
                source_base_fee: 4.435022,
                destination_base_fee: 4.435022,
                is_native: false
            },
            {
                name: "IMX",
                asset: "IMX",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xF57e7e7C23978C3cAEC3C3548E3D615c346e79fF",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 500,
                deposit_fee: 6.377331,
                withdrawal_fee: 2.65567,
                source_base_fee: 0.555555,
                destination_base_fee: 0.555555,
                is_native: false
            },
            {
                name: "SNX",
                asset: "SNX",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 500,
                deposit_fee: 6.676014,
                withdrawal_fee: 4.652934,
                source_base_fee: 0.316455,
                destination_base_fee: 0.316455,
                is_native: false
            }
        ]
    },
    {
        display_name: "BASE",
        internal_name: "BASE_MAINNET",
        native_currency: "ETH",
        logo: "https://cdn.lux.network/bridge/networks/base_mainnet.png",
        is_testnet: false,
        is_featured: false,
        average_completion_time: "00:01:04.0494430",
        chain_id: 56,
        status: "inactive",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: []
    },
    {
        display_name: "Arbitrum",
        internal_name: "ARBITRUM_MAINNET",
        native_currency: "ETH",
        logo: "https://cdn.lux.network/bridge/networks/arbitrum_mainnet.png",
        is_testnet: false,
        is_featured: false,
        average_completion_time: "00:01:04.0494430",
        chain_id: 56,
        status: "inactive",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: []
    },
]

export const sourceNetworks_: Network[] = [
    {
        display_name: "Ethereum",
        internal_name: "ETHEREUM_MAINNET",
        native_currency: "ETH",
        logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
        is_testnet: false,
        is_featured: true,
        average_completion_time: "00:01:04.0494430",
        chain_id: 11155111, //sepolia
        // chain_id: 1,
        status: "active",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: [
            {
                name: "ETH",
                asset: "ETH",
                logo: "https://cdn.lux.network/bridge/currencies/eth.png",
                contract_address: null,
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: true
            },
            {
                name: "BKT",
                asset: "BKT",
                logo: "https://cdn.lux.network/bridge/currencies/bkt.png",
                contract_address: "0x9d62526f5Ce701950c30F2cACa70Edf70f9fbf0F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ASTR",
                asset: "ASTR",
                logo: "https://cdn.lux.network/bridge/currencies/astr.png",
                contract_address: "0x9bBAf650DcD8D3583195715Fc46b1118c3CfDdfd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "LETH",
                asset: "LETH",
                logo: "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
                contract_address: "0x42449554b0c7D85EbD488e14D7D48c6A78D3F9Be",
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: false
            },
            {
                name: "LUSD",
                asset: "LUSD",
                logo: "https://cdn.lux.network/bridge/currencies/lusd.png",
                contract_address: "0xc16ECFE3cB80e142d7110b97a442d4caAA203ABf",
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: false
            },
            {
                name: "ZKS",
                asset: "ZKS",
                logo: "https://cdn.lux.network/bridge/currencies/zks.png",
                contract_address: "0xe4815AE53B124e7263F08dcDBBB757d41Ed658c6",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 10000,
                deposit_fee: 166.865654,
                withdrawal_fee: 65.820981,
                source_base_fee: 26.053974,
                destination_base_fee: 26.053974,
                is_native: false
            },
            {
                name: "USDT",
                asset: "USDT",
                logo: "https://cdn.lux.network/bridge/currencies/usdt.png",
                contract_address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
                decimals: 6,
                status: "active",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 4.68,
                withdrawal_fee: 2.24,
                source_base_fee: 1,
                destination_base_fee: 1,
                is_native: false
            },
            {
                name: "USDC",
                asset: "USDC",
                logo: "https://cdn.lux.network/bridge/currencies/usdc.png",
                contract_address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                decimals: 6,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 3000,
                deposit_fee: 12.79,
                withdrawal_fee: 6.4,
                source_base_fee: 0.99,
                destination_base_fee: 0.99,
                is_native: false
            },
            {
                name: "DAI",
                asset: "DAI",
                logo: "https://cdn.lux.network/bridge/currencies/dai.png",
                contract_address: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 3000,
                deposit_fee: 12.79,
                withdrawal_fee: 6.4,
                source_base_fee: 0.99,
                destination_base_fee: 0.99,
                is_native: false
            },
            {
                name: "LRC",
                asset: "LRC",
                logo: "https://cdn.lux.network/bridge/currencies/lrc.png",
                contract_address: "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 10000,
                deposit_fee: 52.455252,
                withdrawal_fee: 21.830179,
                source_base_fee: 4.435022,
                destination_base_fee: 4.435022,
                is_native: false
            },
            {
                name: "IMX",
                asset: "IMX",
                logo: "https://cdn.lux.network/bridge/currencies/imx.png",
                contract_address: "0xF57e7e7C23978C3cAEC3C3548E3D615c346e79fF",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 500,
                deposit_fee: 6.377331,
                withdrawal_fee: 2.65567,
                source_base_fee: 0.555555,
                destination_base_fee: 0.555555,
                is_native: false
            },
            {
                name: "SNX",
                asset: "SNX",
                logo: "https://cdn.lux.network/bridge/currencies/snx.png",
                contract_address: "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 500,
                deposit_fee: 6.676014,
                withdrawal_fee: 4.652934,
                source_base_fee: 0.316455,
                destination_base_fee: 0.316455,
                is_native: false
            }
        ]
    },
    {
        display_name: "Binance Smart Chain",
        internal_name: "BSC_MAINNET",
        native_currency: "BNB",
        logo: "https://cdn.lux.network/bridge/networks/bsc_mainnet.png",
        is_testnet: false,
        is_featured: false,
        average_completion_time: "00:01:04.0494430",
        chain_id: 56,
        status: "inactive",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: [
            {
                name: "BNB",
                asset: "BNB",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: null,
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: true
            },
            {
                name: "BKT",
                asset: "BKT",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0x9d62526f5Ce701950c30F2cACa70Edf70f9fbf0F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ASTR",
                asset: "ASTR",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0x9bBAf650DcD8D3583195715Fc46b1118c3CfDdfd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 0,
                withdrawal_fee: 0,
                source_base_fee: 0,
                destination_base_fee: 0,
                is_native: false
            },
            {
                name: "ZKS",
                asset: "ZKS",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xe4815AE53B124e7263F08dcDBBB757d41Ed658c6",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 10000,
                deposit_fee: 166.865654,
                withdrawal_fee: 65.820981,
                source_base_fee: 26.053974,
                destination_base_fee: 26.053974,
                is_native: false
            },
            {
                name: "USDT",
                asset: "USDT",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
                decimals: 6,
                status: "active",
                is_deposit_enabled: false,
                is_withdrawal_enabled: false,
                is_refuel_enabled: false,
                max_withdrawal_amount: 0,
                deposit_fee: 4.68,
                withdrawal_fee: 2.24,
                source_base_fee: 1,
                destination_base_fee: 1,
                is_native: false
            },
            {
                name: "USDC",
                asset: "USDC",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                decimals: 6,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 3000,
                deposit_fee: 12.79,
                withdrawal_fee: 6.4,
                source_base_fee: 0.99,
                destination_base_fee: 0.99,
                is_native: false
            },

            {
                name: "LRC",
                asset: "LRC",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 10000,
                deposit_fee: 52.455252,
                withdrawal_fee: 21.830179,
                source_base_fee: 4.435022,
                destination_base_fee: 4.435022,
                is_native: false
            },
            {
                name: "IMX",
                asset: "IMX",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xF57e7e7C23978C3cAEC3C3548E3D615c346e79fF",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 500,
                deposit_fee: 6.377331,
                withdrawal_fee: 2.65567,
                source_base_fee: 0.555555,
                destination_base_fee: 0.555555,
                is_native: false
            },
            {
                name: "SNX",
                asset: "SNX",
                logo: "https://cdn.lux.network/bridge/networks/ethereum_mainnet.png",
                contract_address: "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
                decimals: 18,
                status: "inactive",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: true,
                max_withdrawal_amount: 500,
                deposit_fee: 6.676014,
                withdrawal_fee: 4.652934,
                source_base_fee: 0.316455,
                destination_base_fee: 0.316455,
                is_native: false
            }
        ]
    },
    {
        display_name: "BASE",
        internal_name: "BASE_MAINNET",
        native_currency: "ETH",
        logo: "https://cdn.lux.network/bridge/networks/base_mainnet.png",
        is_testnet: false,
        is_featured: false,
        average_completion_time: "00:01:04.0494430",
        chain_id: 56,
        status: "inactive",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: []
    },
    {
        display_name: "Arbitrum",
        internal_name: "ARBITRUM_MAINNET",
        native_currency: "ETH",
        logo: "https://cdn.lux.network/bridge/networks/arbitrum_mainnet.png",
        is_testnet: false,
        is_featured: false,
        average_completion_time: "00:01:04.0494430",
        chain_id: 56,
        status: "inactive",
        type: "evm",
        refuel_amount_in_usd: 0.5,
        transaction_explorer_template: "https://etherscan.io/tx/{0}",
        account_explorer_template: "https://etherscan.io/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: []
    },

]

export const destinationNetworks: Network[] = [
    {
        display_name: "Lux",
        internal_name: "LUX_MAINNET",
        native_currency: "LUX",
        logo: "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
        is_testnet: false,
        is_featured: true,
        average_completion_time: "00:00:07.7777777",
        chain_id: 7777,
        status: "active",
        type: "evm",
        refuel_amount_in_usd: 1,
        transaction_explorer_template: "https://explore.lux.network/tx/{0}",
        account_explorer_template: "https://explore.lux.network/address/{0}",
        node: "https://eth-mainnet.g.alchemy.com/v2/-z4Zrujiou9ajXAplVapFFWWrPuLPSm7",
        currencies: [
            {
                name: "LUX",
                asset: "LUX",
                logo: "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
                contract_address: null,
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: true
            },
            {
                name: "LETH",
                asset: "LETH",
                logo: "https://cdn.lux.network/bridge/networks/lux_mainnet.png",
                contract_address: "0x42449554b0c7D85EbD488e14D7D48c6A78D3F9Be",
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: false
            },
            {
                name: "LUSD",
                asset: "LUSD",
                logo: "https://cdn.lux.network/bridge/currencies/lusd.png",
                contract_address: "0xc16ECFE3cB80e142d7110b97a442d4caAA203ABf",
                decimals: 18,
                status: "active",
                is_deposit_enabled: true,
                is_withdrawal_enabled: true,
                is_refuel_enabled: false,
                max_withdrawal_amount: 1,
                deposit_fee: 0.001462,
                withdrawal_fee: 0.001462,
                source_base_fee: 0.000456,
                destination_base_fee: 0.000456,
                is_native: false
            },
        ]
    }
]

export const CONTRACTS = {
    11155111: {
        teleporter: "0x568BF299E115D78a1fBa57BafdAe0fD8A26BFb7e",
    },
    7777: {
        teleporter: "0xB2237fb7DBB19Ff09BBD64029064eC05B3C369Ac"
    }
}